osx_image: xcode10.1
language: swift

script:
  - xcodebuild test -enableCodeCoverage YES -project MemoryCache.xcodeproj -scheme MemoryCache -sdk iphonesimulator | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
